library:
  source-dirs: src
tests:
  day3-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day3
copyright: ISC
maintainer: ahouts4@gmail.com
dependencies:
- split
- base >= 4.7 && < 5
name: day3
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Andrew Houts
github: ahouts/day3
license: BSD3
executables:
  day3-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day3
description: Please see the README on GitHub at <https://github.com/ahouts/day3#readme>
