[package]
name = "day7"
version = "0.1.0"
authors = ["Andrew Houts <ahouts4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2.4"
rayon = "1.2.1"
